version: 2
dependencies:
  pre:
    - echo "Starting, TRACER"
    - sudo apt-get update; sudo apt-get install ocaml-nox
    - bash ./.circleci/opam-install.sh
    - sudo make install
  post:
    - echo "Done, TRACER"
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: sudo apt-get update; sudo apt-get install -y software-properties-common && sudo add-apt-repository -y ppa:avsm/ppa && sudo apt-get update; sudo apt-get install -y build-essential ocaml-nox ocaml-native-compilers camlp4-extra opam
      - run:
          name: Test OPAM
          command: opam init --root=/root/.opam && opam update
