version: 2
dependencies:
  pre:
    - echo "Starting, TRACER"
    - sudo apt-get update; sudo apt-get install ocaml-nox
    - bash ./.circleci/opam-install.sh
    - sudo make install
  post:
    - echo "Done, TRACER"
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: sudo apt-get update; sudo apt-get install wget build-essentials ocaml-nox
      - run:
          name: Install OPAM
          command: bash ./.circleci/opam-install.sh
      - run:
          name: Test OPAM
          command: opam update
