version: 2
dependencies:
  pre:
    - echo "Starting, TRACER"
    - sudo apt-get update; sudo apt-get install ocaml-nox
    - bash ./.circleci/opam-install.sh
    - sudo make install
  post:
    - echo "Done, TRACER"
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Test OPAM
          command: opam update
      - run:
          name: Print the Current Time
          command: date
