version: 2
dependencies:
  cache_directories:
    - opam-full-2.0.0-rc2
  pre:
    - sudo apt-get update; sudo apt-get install ocaml-nox
    - bash ./.circleci/opam-install.sh
    - sudo make install
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
