version: 2
dependencies:
  pre:
    - echo "Starting, TRACER"
    - sudo apt-get update; sudo apt-get install ocaml-nox
    - bash ./.circleci/opam-install.sh
    - sudo make install
  post:
    - echo "Done, TRACER"
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - restore_cache:
          key: my-cache
      - checkout
      - save_cache:
          key: my-cache
          paths:
            - /root/project/findlib-1.8.0
            - /root/project/ocaml-4.06.0
      - run:
          name: Install prerequisites
          command: sudo apt-get update; sudo apt-get install -y build-essential opam
      - run:
          name: Install Ocaml
          command: bash ./.circleci/ocaml-install.sh
      - run:
          name: Install findlib
          command: bash ./.circleci/findlib-install.sh
      - run:
          name: Install OPAM-dep
          command: opam init && opam install extlib re re.glob cmdliner cudf dose3.common dose3.algo opam-file-format mccs cppo
      - run:
          name: Install OPAM
          command: bash ./.circleci/opam-install.sh
      - run:
          name: Test OPAM
          command: opam update
