version: 2
dependencies:
  pre:
    - echo "Starting, TRACER"
    - sudo apt-get update; sudo apt-get install ocaml-nox
    - bash ./.circleci/opam-install.sh
    - sudo make install
  post:
    - echo "Done, TRACER"
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - restore_cache:
          key: my-cache
      - checkout
      - save_cache:
          key: my-cache
          paths:
            - /root/project/findlib-1.8.0
            - /root/project/ocaml-4.06.0
      - run:
          name: Install prerequisites
          command: sudo apt-get update; sudo apt-get install -y software-properties-common && sudo add-apt-repository ppa:avsm/ppa && sudo apt-get update; sudo apt-get install -y build-essential ocaml ocaml-native-compilers camlp4-extra opam
      - run:
          name: Test OPAM
          command: opam update
